function contentsList(){
    //問題の単語を格納する連想配列
    var tango = {
      kita : 'hougaku',
      kita2 : 'hougaku',
      minami : 'hougaku',
      higasi : 'hougaku',
      nisi : 'hougaku',
      migi : 'hougaku',
      hidari: 'hougaku',
      doyoubi: 'youbi',
      nitiyoubi: 'youbi',
      nitiyoubi2: 'youbi',
      getuyoubi: 'youbi',
      getuyoubi2: 'youbi',
      mokuyoubi: 'youbi',
      suiyoubi: 'youbi',
      suiyoubi2: 'youbi',
      kayoubi: 'youbi',
      kayoubi2: 'youbi',
      kinnyoubi: 'youbi',
      ototoi: 'itu',
      kyou: 'itu',
      sennsyuu: 'itu',
      kyonenn: 'itu',
      asatte: 'itu',
      asu: 'itu',
      kinou: 'itu',
      rainenn: 'itu',
      raisyuu: 'itu',
      itu: 'itu',
      yoru: 'itu',
      hiru: 'itu',
      asa: 'itu',
      hare: 'tennki',
      kumori: 'tennki',
      kumori2: 'tennki',
      yuki: 'tennki',
      ame: 'tennki',
      atui: 'onndo',
      atatakai: 'onndo',
      samui: 'onndo',
      suzusii: 'onndo',
      ryousinn: 'kannkei',
      ani: 'kannkei',
      kyoudai: 'kannkei',
      tomodati: 'kannkei',
      imouto: 'kannkei',
      ane: 'kannkei',
      simai: 'kannkei',
      musume: 'kannkei',
      kazoku: 'kannkei',
      otouto: 'kannkei',
      musuko: 'kannkei',
      haha: 'kannkei',
      titi: 'kannkei',
      sohu: 'kannkei',
      sobo: 'kannkei',
      dare: 'kannkei',
      siro: 'iro',
      aka: 'iro',
      ao: 'iro',
      kiiro: 'iro',
      kuro: 'iro',
      otona: 'mibunn',
      onnna: 'mibunn',
      kodomo: 'mibunn',
      kodomo2: 'mibunn',
      otoko: 'mibunn',
      roumono: 'nanimono',
      roumono2: 'nanimono',
      tyousya: 'nanimono',
      nanntyousya: 'nanimono',
      omou: 'kannjyou',
      warui: 'kannjyou',
      kanasii: 'kannjyou',
      tanosii: 'kannjyou',
      utukusii: 'kannjyou',
      yoi: 'kannjyou',
      suki: 'kannjyou',
      kirai: 'kannjyou',
      bad: 'kannjyou',
      OK: 'kannjyou',
      hutuu: 'kannjyou',
      gennki: 'kannjyou',
      au: 'dousa',
      kuru: 'dousa',
      iku: 'dousa',
      iku2: 'dousa',
      iu: 'dousa',
      yomu: 'dousa',
      asobu: 'dousa',
      arigatou: 'kaiwa',
      gokurousama: 'kaiwa',
      sayounara: 'kaiwa',
      sumimasenn: 'kaiwa',
      anata: 'daimeisi',
      watasi: 'daimeisi',
      hitobito: 'daimeisi',
      minasann: 'daimeisi',
      doko: 'basyo',
      basyo: 'basyo',
      ie: 'basyo',
      yama: 'basyo',
      kawa: 'basyo',
      yasumi: 'muzokusei',
      nani: 'muzokusei',
      onaji: 'muzokusei',
      namae: 'muzokusei',
      namae2: 'muzokusei',
      uso: 'muzokusei',
      syuwa: 'muzokusei',
      honntou: 'muzokusei',
      tigau: 'muzokusei',
      kamawanai: 'muzokusei'
      
      
     
    };
  
    return tango;
  }
  export default contentsList;